### ISSUE TITLE
Scanning unsupported

### ISSUE THREAD

**Issue by sminodonte** [Loghorn/ant-plus#1]
Hi,
why this message of error?
thanks

ant-plus\build\ant.js:614
        throw 'scanning unsupported';
        ^
scanning unsupported

**Comment by Loghorn** [comment]
If you need to scan, you must instantiate a AntPlusScanner derived class (e.g HeartRateScanner).
Trying to scan with an AntPlusSensor derived class is not supported, so it throws.

**Comment by sminodonte** [comment]
ok, it works now
thanks a lot

**Comment by Loghorn** [comment]
You are welcome.

**Comment by clough360** [comment]
ok, for me this was fixed by using the updated version of the Zadig installer on windows. The version pointed to b the Readme.md is a n old version on SourceForge. The correct version to use is the one on the Zadig website https://zadig.akeo.ie/

Good luck with your issue.
