### ISSUE TITLE
Max sensors limit?

### ISSUE THREAD

**Issue by dburongarcia** [Loghorn/ant-plus#12]
Hello, I would like to know how many sensors would it be able to connect simultaneously? Usually with a USB dongle is 8, but I wonder if it could reach this limit or even overcome it. Thanks

**Comment by Loghorn** [comment]
The limit depends on the actual USB stick and is imposed by hardware, so it can't be surpassed. You can get your stick limit by reading the `maxChannels` property

**Comment by dburongarcia** [comment]
Thanks, so that means the issue https://github.com/Loghorn/ant-plus/issues/10 is solved and there is no software limitation then, even for more than 8 sensors? I asked because there are some special USB dongles that allow 40 simultaneous connections.

**Comment by Loghorn** [comment]
As far as I know there is no software limit but I never tried those dongles: If you do, let me know the result. Thank you.
