### ISSUE TITLE
ANT+ FE-C device profile

### ISSUE THREAD

**Issue by acontia** [Loghorn/ant-plus#17]
Hi,
Are there any plans to implement the Fitness Equipment Controls (FE-C) device profile?
See section 2) of https://www.thisisant.com/developer/ant-plus/device-profiles/#525_tab

Thanks!

**Comment by cleeland** [comment]
Curious about this as well.  Even if there are no specific plans, an outline of what might need to be done in order to implement it would be helpful to bootstrap a motivated implementer.

**Comment by Loghorn** [comment]
Unfortunately this library is made essentially to just receive data from ANT+ devices, not to control them, so adding support for FE-C is not easy and will probably involve a major rewrite of it.
I don't have the time and motivation needed to do this, but if someone does I'll be very happy to accept a PR.

**Comment by cleeland** [comment]
Thanks for the quick reply!

It appears that [this fork](https://github.com/gdoumen/ant-plus/blob/master/sample/fitness-equipment-advanced.js} is starting down the path of supporting controlling.  In my case, I actually want to BE the FE-C device, not talk to another device that is an FE-C device.
