### ISSUE TITLE
What's the meaning of attaching HR sensors ?

### ISSUE THREAD

**Issue by shmatul** [Loghorn/ant-plus#21]
Hello

I am able to receive the HR data from multiple devices using only 1 sensor initialized.
In every beat I receive hbData simultaneously from all devices and store the data according to the given serial number.

I never call the attach method and actually don't understand why I need it all, or  what's the meaning of attaching the sensor to a channel.

Can anyone help me figure this out?

Thanks!

**Comment by Loghorn** [comment]
I don't understand: if you don't attach the sensor, you won't get any data, unless you are using a scanner that doesn't have an attach method

**Comment by shmatul** [comment]
Got it.
I was using the scanner, thanks.

**Comment by shmatul** [comment]
@Loghorn  - is it necessary to attach each and every single HR sensor to get relevant data?
Can I just used the scanner and not attach sensors?
Is attaching a sensor doing something to the device?

**Comment by bierzorutas** [comment]
+1 to the shmatul question, I also would like to know the answer. 
Thanks in advance @Loghorn
