### ISSUE TITLE
Adding bicycle speed/cadence sensor

### ISSUE THREAD

**Issue by mattdsteele** [Loghorn/ant-plus#3]
I'd like to capture data from a [Garmin GSC-10 speed/cadence sensor](http://www.amazon.com/Garmin-Speed-Cadence-Bike-Sensor/dp/B000BFNOT8) I've got attached to my bike.

It looks like this is a different type of device than either the heart rate monitor or the stride/speed/distance sensors currently in the repository. How would one go about adding this sensor type? Is there a website for ANT+ sensor specs I could reference, perhaps?

**Comment by Loghorn** [comment]
You can find all the specification of ANT+ protocol at https://www.thisisant.com/
Feel free to submit a PR once you have implemented it :smile:
